# Yarn PnP 설정
nodeLinker: pnp
pnpMode: strict

# TypeScript 지원
packageExtensions:
  '@types/node@*':
    dependencies:
      'typescript': '*'

# 캐시 설정
enableGlobalCache: true
compressionLevel: mixed

# 네트워크 설정
httpTimeout: 300000
