version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: lostark123
      MYSQL_DATABASE: lostark_cache
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  lostark-api:
    build: .
    ports:
      - "3000:3000"  # REST Service
      - "3001:3001"  # UDP Service
    environment:
      - NODE_ENV=production
      - CACHE_REDIS_URL=redis://redis:6379
      - CACHE_MYSQL_HOST=mysql
      - CACHE_MYSQL_PASSWORD=lostark123
    depends_on:
      - redis
      - mysql
    restart: unless-stopped

volumes:
  redis_data:
  mysql_data: