version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_SCHEMA}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3300:${DB_PORT}"
      - "33060:33060"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lrk-network

  app:
    build: .
    restart: always
    ports:
      - "3000:${PORT}"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      PREFIX: ${PREFIX}
    networks:
      - lrk-network

volumes:
  db_data:

networks:
  lrk-network:
